// Messages
const ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
const FATAL_ERROR = "FATAL_ERROR_IN_RUNTIME";
const INVALID_OPERATION = "INVALID_OPERATION";
const CLOSE_MARKET = "CLOSE_MARKET";
const INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE";
const INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK";
const STOCK_NOT_FOUND = "STOCK_NOT_FOUND";
const DUPLICATE_OPERATION = "DUPLICATE_OPERATION";

// Dates and Times
const START_HOUR = "06:00:00"
const END_HOUR = "15:00:00"
const DEFAULT_INTERVAL = 5;

export {
    INVALID_OPERATION,
    FATAL_ERROR,
    ACCOUNT_NOT_FOUND,
    CLOSE_MARKET,
    INSUFFICIENT_BALANCE,
    INSUFFICIENT_STOCK,
    DUPLICATE_OPERATION,
    STOCK_NOT_FOUND,
    START_HOUR,
    END_HOUR,
    DEFAULT_INTERVAL,
}